### ISSUE TITLE
cannot use pykaldi from conda: `GLIBC_2.23' not found

### ISSUE THREAD

**Issue by mmmaat** [pykaldi/conda-package#1]
Dear pykaldi developers,

I tried to use pykaldi from conda (just having a `conda install -c pykaldi pykaldi` in a fresh python-3.7 environment, but when trying the [example notebook](https://github.com/pykaldi/pykaldi/blob/master/examples/notebooks/Extracting%20MFCC%20features.ipynb) I get this error:
```
In [1]: from kaldi.util.table import MatrixWriter
ImportError: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /home/mbernard/.conda/envs/pykaldi/lib/python3.7/site-packages/kaldi/fstext/../lib/libfstscript.so.8)
```
My system is a centos 7 with glibc 2.17. Note that, when compiled from sources, all is working as expected.

So here is my question: is it possible to change the conda image so that it use a glibc from conda instead of the system one?

Thanks!

**Comment by vrmpx** [comment]
Thank you for your comment. We started working on improving the coverage of the conda package. Specifically by building the conda package for centos. However this might take a while as it is not a simple task and we (me and @dogancan) are not that familiar with centos. Any tips on how to build from source in centos? 

With regard to your question: it sounds possible to either modify the library paths to prioritize conda glibc or re-write the rpaths to use the conda glibc (e.g., by using patchelf). But that may induce unexpected behavior down the line.

**Comment by mmmaat** [comment]
Ok thank you, I never did any conda package so I can't help you on that hand. But for the compilation on centos, just following https://github.com/pykaldi/pykaldi#from-source is fine.

* The install of dependencies change a little bit, but nothing complicated: `yum install autoconf automake cmake3 curl graphviz atlas-devel libtool make subversion unzip wget zlib-devel`

* Then you must make a shortcut from cmake3 to cmake: `ln -s /bin/cmake3 /usr/bin/cmake `

* Finally you need a version of git more recent that the one in the official repos (supporting the `-c` option). So I installed alternatives repos from https://ius.io. Then `yum install git2u`.

**Comment by vrmpx** [comment]
Hey @mmmaat, 
I just updated the packages in anaconda. These are built in CentOS7.

Could you try them out and see if this issue persists? 

You may have to create a new env or update your current installation, make sure you have the ones that end in `_6` (e.g.,`pykaldi:        0.0.9-py36h7c1a757_6  pykaldi` )

**Comment by mmmaat** [comment]
Thank you, all is working now (I used the latest version suffixed `_7`).

**Comment by vrmpx** [comment]
That is great!
Thanks for letting me know
